### PR TITLE
Configurable way to warn if translation does not exist

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria
1. warning in console if translation doesn't exist
### Tasks
- {{list developer tasks here}}
### Additional Notes
- {{list additional notes here, remove if not applicable}}

### CODE REVIEW

**Comment by baohx2000** [comment]
:m: :star:

**Comment by paulstatezny** [comment]
:hand:

**Comment by paulstatezny** [comment]
:pray:

**Comment by paulstatezny** [comment]
:+1:

**Pull request merged**
